Dz6
MadMaX-74/marketplace pull request #8
Opened 2024-09-15 11:10 UTC by MadMaX-74

2024-09-16 08:18 UTC, evgnep commented on gradle/libs.versions.toml
> +cor = { module = "ru.otus.todo.libs:todo-projects-lib-cor" }
а разве сюда надо добавлять зависимости из самого проекта?

2024-09-16 08:20 UTC, evgnep commented on todo-projects/todo-projects-biz/src/commonMain/kotlin/TodoProcessor.kt
> +            }
а где команды удаления и фильтрации? Или у вас их нет?

2024-09-16 08:21 UTC, evgnep commented on todo-projects/todo-projects-biz/src/commonMain/kotlin/stubs/StubDeleteSuccess.kt
> +fun ICorChainDsl<TodoContext>.stubDeleteSuccess(title: String, corSettings: TodoCorSettings) = worker {
хотя стаб для успешного удаления есть - видимо вы забыли добавить в цепочку?

2024-09-16 08:23 UTC, evgnep commented on todo-projects/todo-projects-biz/src/commonTest/kotlin/stub/TodoListStubTest.kt
> +            command = TodoCommand.LIST,
У вас же не было команды LIST в цепочке - и кстати сборка в гитхабе падает. Не поэтому ли?

2024-09-16 08:23 UTC, evgnep requested changes
Добавьте команды LIST / DELETE, а в остальном все ок

2024-09-17 07:21 UTC, MadMaX-74 commented on gradle/libs.versions.toml
> +cor = { module = "ru.otus.todo.libs:todo-projects-lib-cor" }
да, я посмотрел как сделано в основном проекте, там так. Просто иначе это не работает

2024-09-17 07:33 UTC, MadMaX-74 commented on todo-projects/todo-projects-biz/src/commonMain/kotlin/TodoProcessor.kt
> +            }
Я видимо случайно удалил, вернул

2024-09-17 07:34 UTC, MadMaX-74 commented on todo-projects/todo-projects-biz/src/commonMain/kotlin/stubs/StubDeleteSuccess.kt
> +fun ICorChainDsl<TodoContext>.stubDeleteSuccess(title: String, corSettings: TodoCorSettings) = worker {
все верно, немного запутался тут

2024-09-17 07:34 UTC, MadMaX-74 commented on todo-projects/todo-projects-biz/src/commonTest/kotlin/stub/TodoListStubTest.kt
> +            command = TodoCommand.LIST,
комманда LIST была всегда - это список задач. У меня стандартный CRUD и List запрос для списка

2024-09-18 08:28 UTC, merged